driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: oracle-6.8

  - name: centos-7.3
  - name: oracle-7.3

  - name: fedora-25
    run_list: yum::dnf_yum_compat

  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-7.11
  - name: debian-8.6

suites:
  - name: client
    run_list:
      - recipe[test::client]
    attributes:

  - name: server
    run_list:
      - recipe[test::server]
    attributes:
